language: ruby
rvm: 2.3.0
branches:
  only:
  - now
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem update --system
  - gem install bundler
script:
  - JEKYLL_ENV=production bundle exec jekyll build
