language: ruby
rvm:
  - 2.1

branches:
  only:
    - source

env:
  global:
    - secure: "CpTJ0+CL4UNzkOT+t4rLeH0RK7p9kSlfOwMKCFdNMHFXVLBujKHPUiGlw3xqFJj4ok90TQyRjxnbgOgh2xaYUqfV8tWxr9nhhlD4Vbb9N8R7ZxBrfWXpt06g1jx3WjViEJJJawK4WMVFUABzpq71RVdqCM147knmXk1B8rRM93M/oiPn1hRUAvm7+U+IglIACFPVy/A1hEod8cjxeWFIxUtcxVLshAqmhVtDT2Ffiw8/wXog2CQYypuMxNbpntmqW8AxSi25ttfOOsSnqMKLOYAtReii95RChZBjSveYWDITIeK/sPA4t6yqL7MMU31VMaQ4wgtta5otvu69kg5WC8EkG7VLL8oyg7Bul0sReDcFSV4Z7zTIq/t1jz1iMjC9gNBtsN9GhJFiPGe+9xWo+M7ZaFXiuT9ceWJae5Hnya5SFpJGvMavGypqlv5CU9k+sBJ0prVd1cGbLyXc6CEkp6XRlgZWD9eaoGLHgUoI4woLL/JqLQWcgh8puhu/m0nb+ARfNMItt0XTMvJMMVsaIpJuS8OTYvHKeIZRoS42jafojBMreIUcVV8v8eOW7QiejEnx6Qcjo0TyX2ilcE/GNYWrsHOCzpBzNbTZpoQ3h7K5bKffQIbTmZtV84BQvOUZXRfyTvNK6lo/01l9GnSlhkSpzQvgwZgXeOyj8aO7atY="
    - secure: "mGY+AGyc38QoOJROeLN4y2rKfyziIW3kJGpfr2f6g8WsbLF7P1JGA19iRpbQt9pHJkxIdpMrkPZxhd4N8LE9SSh/RkZ6OgakY74Ttyd+YwSOl+rT1V/7WhdpYr5vGH6tUcqfvfrX0VqMIDMWJTzLhP5hyh/dAVoN+naGxLDrOY+A0wJM05//i7FZt31Ah9smPMac6ICWJ5PqK4LHUDlsxQWMecxkajOKeYatK75gGhc2AhnS9eqpcaWF1XRGvdU1C4aCN18hJ3p/tQoAnlAaVw7qM7akJ6pAjabsXTtTEB8W2xFuCPXpjkAL2zzcnfyn8LDeiCoXQkbGQpK3Z7z/6+eYEfN/bf2Cm9j3hQpqnm8xV+bLgGJUR/M/Midg54y3m3A9AhRH4no/8Zyi460vgBfsxFAh7dViFmgfUxjJ1TITUsFY7xgz45qFKl4C1DS5T1ZfGsfOg1cYbd2aui+nExs4vUuLf72PP2AQMhWCnU7idcIcn1HFe41f7WJ2QS9pdfodMZkKAwbMRztjAUfYoMK2ZJqgyGiCghUiOyZ8+mfAJa9AyROroW7Qk1rcae4jocvf2xsosnzV0fnxLz4cTT+Hfzhn+q00OU5vHvV7TdawBQJFdOz6SimMFtNwB3+6R4XOIAyUA+AwHSPfkiTfx9jHv7DeknfG3uInj/yNVlg="

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script:
  - bundle exec jekyll build --drafts && bash ./purge-cache.sh

notifications:
  email: false
