# Site wide configuration

title: /home/cubarco
locale: zh_CN
description: PWN for fun.
logo: #site-logo.png
search: true
url: https://cub4r.co


# Jekyll configuration

permalink:   /blog/:year/:month/:title/
markdown:    kramdown
highlighter: rouge
excerpt_separator: ""
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-gist

gist:
  noscript: false

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "vendor", "purge-cache.sh", "now.json", "build.sh"]


# Site owner
owner:
  name: Cubarco
  avatar: matrix.png
  email: me at cub4r.co
  disqus-shortname: cubarco
  twitter: Cube_Lin
  facebook:
  github: cubarco
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram:
  flickr: #username
  tumblr: #username
  google:
    plus:
    analytics: UA-54867602-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
