name: Build & deploy jekyll site.

on:
  push:
    branches:
      - source-gh-actions

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build & deploy to github pages
        uses: cubarco/jekyll-action@master
        if: ${{ github.ref == 'refs/heads/source-gh-actions' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          use_tag: true
          keep_history: true
          target_branch: "gh-pages"

      - name: Deploy to fly.io
        if: ${{ github.ref == 'refs/heads/source-gh-actions' }}
        working-directory: ./_site
        uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy"

      - name: Build only
        uses: cubarco/jekyll-action@master
        if: ${{ github.ref != 'refs/heads/source-gh-actions' }}
        with:
          build_only: true
