name: Build & deploy jekyll site.

on:
  push:
    branches:
      - source-gh-actions
  pull_request:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_PROJECT_PATH: /github/workspace/.fly

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install purgecss -g

      - name: Build & deploy to github pages
        if: ${{ github.ref == 'refs/heads/source-gh-actions' }}
        uses: cubarco/jekyll-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          use_tag: true
          #keep_history: true
          target_branch: "gh-pages"
          build_dir: /github/workspace/.fly/jekyll_build

      - name: Purge main.css
        if: ${{ github.ref == 'refs/heads/source-gh-actions' }}
        working-directory: /github/workspace/.fly/jekyll_build
        run: "purgecss --css ./assets/css/main.css --content ./**/*.html --output ./assets/css"

      - name: Deploy to fly.io
        if: ${{ github.ref == 'refs/heads/source-gh-actions' }}
        uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy"

      - name: Build only
        if: ${{ github.ref != 'refs/heads/source-gh-actions' }}
        uses: cubarco/jekyll-action@master
        with:
          build_only: true
