name: Build & deploy jekyll site.

on:
  push:
    branches:
      - source-gh-actions
  pull_request:

env:
  FLY_PROJECT_PATH: /github/workspace/.fly

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - name: GEM cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('./Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: NPM cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Build & deploy to github pages
        if: ${{ github.ref == 'refs/heads/source-gh-actions' }}
        uses: cubarco/jekyll-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          use_tag: true
          #keep_history: true
          target_branch: "gh-pages"
          build_dir: /github/workspace/.fly/jekyll_build
          purgecss: false

      - name: Deploy to fly.io
        if: ${{ github.ref == 'refs/heads/source-gh-actions' }}
        uses: superfly/flyctl-actions@1.1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy"

      - name: Build only
        if: ${{ github.ref != 'refs/heads/source-gh-actions' }}
        uses: cubarco/jekyll-action@master
        with:
          build_only: true
