name: Build & deploy jekyll site.

on:
  push:
    branches:
      - source-gh-actions
  pull_request:

env:
  FLY_PROJECT_PATH: /github/workspace/.fly

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: npm-${{ hashFiles('package-lock.json') }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
          
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build & deploy to github pages
        if: ${{ github.ref == 'refs/heads/source-gh-actions' }}
        uses: cubarco/jekyll-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          use_tag: true
          #keep_history: true
          target_branch: "gh-pages"
          build_dir: /github/workspace/.fly/jekyll_build
          purgecss: false

      - name: Purge Cloudflare cache
        if: ${{ github.ref == 'refs/heads/source-gh-actions' }}
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

      # - name: Deploy to fly.io
      #   if: ${{ github.ref == 'refs/heads/source-gh-actions' }}
      #   uses: superfly/flyctl-actions@1.1
      #   env:
      #     FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      #   with:
      #     args: "deploy"

      - name: Build only
        if: ${{ github.ref != 'refs/heads/source-gh-actions' }}
        uses: cubarco/jekyll-action@master
        with:
          build_only: true
